#!/bin/sh

# Basic command convenience
alias ls='ls --color=auto --almost-all'
alias grep='grep --color=auto'
alias mv='mv -i'
alias cp='cp -i'

# Programs
z() { zathura --fork "$@" 2>/dev/null }
gccfh() { gcc -fdiagnostics-color=always -g -std=c99 -Wall -Wextra -pedantic -Wno-unused-parameter "$1" -o "${1::-2}" }
alias n='nvim'

# Easier directory access
alias cd='cd '
alias cloud='/data/Senfcloud/'
alias brokencars='/data/Senfcloud/broken_cars/'
alias notes='/data/Senfcloud/Notes/'
alias fh='/data/Senfcloud/fh/'
